import = [
  "~/.config/alacritty/alacritty-theme/themes/everforest.toml"
]

[colors]
#primary = { background = "#111111", foreground = "#999999" }
primary = { background = "#111111", foreground = "#999999" }


[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 100

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 13
